version: "3"

services:
  api:
    build: API/.
    ports:
      - 5000:5000
    networks:
      - code_generator_network
    volumes:
      - /home/fred/Formation/Certifs/Chef_d_oeuvre/code_generator/API/api.py:/src/api.py

  front:
    build: Front/.
    ports:
      - 3000:3000
    networks:
      - code_generator_network
    volumes:
      - /home/fred/Formation/Certifs/Chef_d_oeuvre/code_generator/Front/:/src/

networks:
  code_generator_network: