version: "3"

services:
  api:
    build: API/.
    ports:
      - 5000:5000
    networks:
      - emotion_detector_network
    volumes:
      - /home/fred/Formation/Certifs/detecteur_emotion/emotion_detector/API/:/src/

  front:
    build: Front/.
    ports:
      - 3000:3000
    networks:
      - emotion_detector_network
    volumes:
      - /home/fred/Formation/Certifs/detecteur_emotion/emotion_detector/Front/:/app/

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: emotion_detector
      MYSQL_PASSWORD: emotion_detector
      MYSQL_DATABASE: emotion_detector_db
    ports:
      - 3307:3306
    networks:
      - emotion_detector_network
    volumes:
     - db_emotion_detector:/var/lib/mysql
    
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - emotion_detector_network


networks:
  emotion_detector_network:


volumes:
  db_emotion_detector: